/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './index';
export const AutoFitTextModuleNgFactory:i0.NgModuleFactory<i1.AutoFitTextModule> = i0.ɵcmf(i1.AutoFitTextModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.AutoFitTextModule,i1.AutoFitTextModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RhbmllbGdlay9XZWJQcm9qZWN0cy9uYXRpdmVzY3JpcHQtYXV0by1maXQtdGV4dC9zcmMvYW5ndWxhci9pbmRleC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9kYW5pZWxnZWsvV2ViUHJvamVjdHMvbmF0aXZlc2NyaXB0LWF1dG8tZml0LXRleHQvc3JjL2FuZ3VsYXIvaW5kZXgudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OzsifQ==
